// Dart generator: a FlagKey enum, a defaults map, and a TypedFlags wrapper with
// one strongly-typed getter per flag over a CheckgateClient's getValue().

import { camelCase, dedupeIdentifiers, dartLiteral, safeDartIdent, zeroValue } from '../util.js'

const DART_TYPE = { boolean: 'bool', string: 'String', integer: 'int', json: 'dynamic' }

function header(meta) {
  return [
    '// AUTO-GENERATED by @checkgate/cli — do not edit by hand.',
    `// Source: ${meta.source}`,
    `// Flags: ${meta.count}`,
    '',
  ].join('\n')
}

export function generate(flags, meta) {
  const idents = dedupeIdentifiers(flags.map(f => safeDartIdent(camelCase(f.key))))
  const out = [header(meta)]

  // FlagKey enum (each member carries its wire key string).
  if (flags.length === 0) {
    out.push('// No flags defined.')
    out.push('enum FlagKey { none }\n')
  } else {
    out.push('enum FlagKey {')
    flags.forEach((f, i) => {
      const sep = i === flags.length - 1 ? ';' : ','
      out.push(`  ${idents[i]}(${dartLiteral(f.key)})${sep}`)
    })
    out.push('')
    out.push('  const FlagKey(this.key);')
    out.push('  final String key;')
    out.push('}\n')
  }

  // Defaults map.
  out.push('const Map<String, Object?> kFlagDefaults = <String, Object?>{')
  for (const f of flags) {
    const value = f.default !== undefined ? f.default : zeroValue(f.type)
    out.push(`  ${dartLiteral(f.key)}: ${dartLiteral(value)},`)
  }
  out.push('};\n')

  // Typed wrapper. `_client` is dynamic so this file needs no SDK import.
  out.push('/// Wrap a CheckgateClient for type-safe flag access.')
  out.push('///')
  out.push('/// ```dart')
  out.push('/// final flags = TypedFlags(checkgate);')
  out.push('/// ```')
  out.push('class TypedFlags {')
  out.push('  TypedFlags(this._client);')
  out.push('  final dynamic _client;')
  flags.forEach((f, i) => {
    const value = f.default !== undefined ? f.default : zeroValue(f.type)
    const dartType = DART_TYPE[f.type]
    const cast = dartType === 'dynamic' ? '' : ` as ${dartType}`
    out.push('')
    out.push(`  ${dartType} ${idents[i]}(String userKey, [Map<String, String> attrs = const {}]) =>`)
    out.push(`      _client.getValue(${dartLiteral(f.key)}, userKey, attrs, ${dartLiteral(value)})${cast};`)
  })
  out.push('}')

  return out.join('\n') + '\n'
}
