// Rust generator: a FlagKey enum with as_str()/ALL, and a `defaults` module of
// typed constants. Dependency-free — `json` flags' defaults are emitted as raw
// JSON string constants so the output needs no serde.

import { pascalCase, upperSnakeCase, dedupeIdentifiers, rustLiteral, zeroValue } from '../util.js'

const RUST_TYPE = { boolean: 'bool', string: '&str', integer: 'i64', json: '&str' }
const RUST_KIND = { boolean: 'bool', string: 'str', integer: 'i64', json: 'json' }

function header(meta) {
  return [
    '// AUTO-GENERATED by @checkgate/cli — do not edit by hand.',
    `// Source: ${meta.source}`,
    `// Flags: ${meta.count}`,
    '',
  ].join('\n')
}

export function generate(flags, meta) {
  const variants = dedupeIdentifiers(flags.map(f => pascalCase(f.key)))
  const constNames = dedupeIdentifiers(flags.map(f => upperSnakeCase(f.key)))
  const out = [header(meta)]

  // Enum of flag keys.
  out.push('/// Compile-time set of known Checkgate flag keys.')
  out.push('#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]')
  if (flags.length === 0) {
    out.push('pub enum FlagKey {}')
  } else {
    out.push('pub enum FlagKey {')
    flags.forEach((_, i) => out.push(`    ${variants[i]},`))
    out.push('}')
  }
  out.push('')

  // as_str() + ALL.
  out.push('impl FlagKey {')
  out.push('    /// The wire key string used by the Checkgate API and SDKs.')
  out.push('    pub const fn as_str(&self) -> &\'static str {')
  if (flags.length === 0) {
    out.push('        match *self {}')
  } else {
    out.push('        match self {')
    flags.forEach((f, i) => out.push(`            FlagKey::${variants[i]} => ${JSON.stringify(f.key)},`))
    out.push('        }')
  }
  out.push('    }')
  out.push('')
  out.push('    /// Every known flag, in a stable order.')
  out.push(`    pub const ALL: &'static [FlagKey] = &[${variants.map(v => `FlagKey::${v}`).join(', ')}];`)
  out.push('}')
  out.push('')

  out.push('impl core::fmt::Display for FlagKey {')
  out.push('    fn fmt(&self, f: &mut core::fmt::Formatter<\'_>) -> core::fmt::Result {')
  out.push('        f.write_str(self.as_str())')
  out.push('    }')
  out.push('}')
  out.push('')

  // Typed default constants.
  out.push('/// Typed default values mirroring each flag\'s configured default.')
  out.push('/// `json` flags are emitted as raw JSON string constants.')
  out.push('pub mod defaults {')
  flags.forEach((f, i) => {
    const value = f.default !== undefined ? f.default : zeroValue(f.type)
    out.push(`    pub const ${constNames[i]}: ${RUST_TYPE[f.type]} = ${rustLiteral(value, RUST_KIND[f.type])};`)
  })
  out.push('}')

  return out.join('\n') + '\n'
}
