// TypeScript generator: a FlagKey union, per-flag value types, defaults, and a
// thin type-safe wrapper over a Checkgate client's getValue()/isEnabled().

import { tsLiteral, zeroValue } from '../util.js'

const TS_TYPE = { boolean: 'boolean', string: 'string', integer: 'number', json: 'unknown' }

function header(meta) {
  return [
    '// AUTO-GENERATED by @checkgate/cli — do not edit by hand.',
    `// Source: ${meta.source}`,
    `// Flags: ${meta.count}`,
    '',
  ].join('\n')
}

export function generate(flags, meta) {
  const out = [header(meta)]

  // FlagKey union.
  if (flags.length === 0) {
    out.push('export type FlagKey = never\n')
  } else {
    out.push('export type FlagKey =')
    out.push(flags.map(f => `  | ${tsLiteral(f.key)}`).join('\n') + '\n')
  }

  // Per-flag value types.
  out.push('export interface FlagValueTypes {')
  for (const f of flags) out.push(`  ${tsLiteral(f.key)}: ${TS_TYPE[f.type]}`)
  out.push('}\n')

  // Ordered list of keys.
  out.push(`export const FLAG_KEYS = [${flags.map(f => tsLiteral(f.key)).join(', ')}] as const\n`)

  // Defaults, keyed by flag.
  out.push('export const FLAG_DEFAULTS: { readonly [K in FlagKey]: FlagValueTypes[K] } = {')
  for (const f of flags) {
    const value = f.default !== undefined ? f.default : zeroValue(f.type)
    out.push(`  ${tsLiteral(f.key)}: ${tsLiteral(value)},`)
  }
  out.push('}\n')

  // Minimal client shape so the generated file needs no SDK import.
  out.push(`export interface CheckgateLike {
  getValue(flagKey: string, userKey: string, userAttributes?: Record<string, string>, defaultValue?: unknown): unknown
  isEnabled(flagKey: string, userKey: string, userAttributes?: Record<string, string>): boolean
}
`)

  // Type-safe wrapper.
  out.push(`/**
 * Wrap a Checkgate client so flag keys are checked at compile time and each
 * value comes back with its declared type. The flag's configured default is
 * supplied automatically when the flag is missing.
 */
export function typedFlags(client: CheckgateLike) {
  return {
    getValue<K extends FlagKey>(key: K, userKey: string, attrs?: Record<string, string>): FlagValueTypes[K] {
      return client.getValue(key, userKey, attrs, FLAG_DEFAULTS[key]) as FlagValueTypes[K]
    },
    isEnabled(key: FlagKey, userKey: string, attrs?: Record<string, string>): boolean {
      return client.isEnabled(key, userKey, attrs)
    },
  }
}
`)

  return out.join('\n')
}
